pin fury==0.7.1 to fix breakage
Version 0.8.0 causes test_dipy to break with ImportError: cannot import name 'vtk' from 'fury.window' 

http://b/217761018