Pin tensorflow_probability to work with TF 2.4.1
The latest version of `tensorflow_probability` is not compatible with
our version of TF:

```
ImportError: This version of TensorFlow Probability requires TensorFlow
version >= 2.5; Detected an installation of version 2.4.1. Please
upgrade TensorFlow to proceed```

Pinning & adding a test to prevent regression.

http://b/194837139