Pin pytorch-lightning & torchmetrics.
Latest versions causing the following error at runtime:

```
...
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/utilities/imports.py", line 33, in _module_available
    return find_spec(module_path) is not None
  File "/opt/conda/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: transformers.__spec__ is None
```

Also, remove /opt/conda/lib from LD_LIBRARY_PATH only when fetching
packages over https using apt.

Otherwise, this is causing an issue with scipy which expects a different
version of glibc.

http://b/198635596