Disable JAX memory preallocation
This is causing other GPU library tests to fail because no GPU memory is
available with errors like:

```
lightgbm.basic.LightGBMError: Memory Object Allocation Failure
```

BUG=173553533