Pin pytorch & torch* libs.
pytorch 1.6 was released. However, a new version of torchaudio
hasn't been released yet which is causing runtime errors:

```
OSError: /opt/conda/lib/python3.7/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

BUG=162357958