Clean up lightgbm install and fix build (#1488)
Bumping up the base image version to the latest. 

Good news, Colab installs lightgbm on both CPU and GPU, 
Bad news seems like the way they installed the package seems to give
issues.

I assume they install lightgbm in a similar manner to us, build the
wheel and install in a tmp folder.

UV PIP doesn't like this and errors at install requirement file step:
error: Distribution not found at:
file:///tmp/lightgbm/LightGBM/dist/lightgbm-4.5.0-py3-none-linux_x86_64.whl

Removing our pin on the package fixes the build.

I could also introduce a pin for lightgbm, but this could be
problematic, as we'll continuously have to update the pining.